spring.application.name=world-cup
spring.datasource.url=jdbc:mysql://localhost:3306/worldcup_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true